### ISSUE TITLE
Potential security issue in src/p_saveg.c: Missing pointer dereference in sizeof

### ISSUE THREAD

**Issue by monocle-ai** [siva-msft/libretro-prboom#6]
The operand to sizeof is the same as the pointer in a memory access. The developer likely intended to calculate the size of the object pointed to but forgot to dereference the pointer in the sizeof. The following code locations use the size of a pointer instead of the actual object's size:
---

1 instance of this defect were found in the following locations:
---
**Instance 1**
File : `src/p_saveg.c` 
Function: `intrinsic.memcpy` 
https://github.com/siva-msft/libretro-prboom/blob/a0a0c34a48446760f82706be95dc3e8d3bca5ad8/src/p_saveg.c#L365
Code extract:

```cpp
        // seeing player anymore.

        if (((mobj_t*)th)->lastenemy && ((mobj_t*)th)->lastenemy->thinker.function == P_MobjThinker) {
          memcpy (save_p + sizeof(void*), &(((mobj_t*)th)->lastenemy->thinker.prev), sizeof(void*)); <------ HERE
	}

```

**Comment by siva-msft** [comment]
Filter out issues with void * as sizeofarg
